Added Runner Interface +++ Modified scripts(pigsh not working for spark) +++ Some other adaptions

diff --git a/script/pigsh b/script/pigsh
--- a/script/pigsh
+++ b/script/pigsh
@@ -1,3 +1,50 @@
-#!/bin/sh
-PIG_LIB=`dirname $0`/../target/scala-2.11/pigparser_2.11-1.0.jar
-scala -classpath $PIG_LIB dbis.pig.PigREPL $*
+#!/bin/bash
+#PIG_LIB=`dirname $0`/../target/scala-2.11/pigparser_2.11-1.0.jar
+
+echo '
+ ____  _         ____  _          _ _ 
+|  _ \(_) __ _  / ___|| |__   ___| | |
+| |_) | |/ _` | \___ \|  _ \ / _ \ | |
+|  __/| | (_| |  ___) | | | |  __/ | |
+|_|   |_|\__, | |____/|_| |_|\___|_|_|
+         |___/                        
+'
+
+if [ -z "$PIG_LIB" ]; then
+    echo "Please set PIG_LIB to your PigCompiler jar file"
+    exit 1
+else
+    CP=$PIG_LIB
+fi
+
+if [ "$#" -ne 1 ]; then
+    echo "Illegal number of parameters. Required 1"
+    exit 1
+else
+    if [ "$1" == "spark" ]; then
+        if [ -z "$SPARK_JAR" ]; then
+            echo "Please set SPARK_JAR to your Spark jar file"
+            exit 1
+        else
+            CP=$SPARK_JAR:$CP
+        fi
+#        if [ -z "$HADOOP_JAR" ]; then
+#            echo "Please set HADOOP_JAR to your Hadoop jar file"
+#            exit 1
+#        else
+#            CP=$HADOOP_JAR:$CP
+#        fi
+    elif [ "$1" == "flink" ]; then
+        if [ -z "$FLINK_JAR" ]; then
+            echo "Please set FLINK_JAR to your Flink jar file (built with scala 2.11)"
+            exit 1
+        else
+            CP=$FLINK_JAR:$CP
+        fi
+    else
+        echo "Unsupported Backend: $1. Supported: spark, flink"
+        exit 1
+    fi
+fi
+
+java -Dscala.usejavacp=true -classpath $CP dbis.pig.PigREPL $*
